[2025-08-12T12:38:04.954+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T12:38:04.985+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_flares_train_12h.mlflow_ping scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T12:38:04.992+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_flares_train_12h.mlflow_ping scheduled__2025-08-12T00:00:00+00:00 [queued]>
[2025-08-12T12:38:04.993+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2025-08-12T12:38:05.004+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): mlflow_ping> on 2025-08-12 00:00:00+00:00
[2025-08-12T12:38:05.012+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'solar_flares_train_12h', 'mlflow_ping', 'scheduled__2025-08-12T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/solar_flares_train_12h.py', '--cfg-path', '/tmp/tmpdoiionrw']
[2025-08-12T12:38:05.015+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3162) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T12:38:05.015+0000] {standard_task_runner.py:91} INFO - Job 124: Subtask mlflow_ping
[2025-08-12T12:38:05.015+0000] {standard_task_runner.py:63} INFO - Started process 3163 to run task
[2025-08-12T12:38:05.065+0000] {task_command.py:426} INFO - Running <TaskInstance: solar_flares_train_12h.mlflow_ping scheduled__2025-08-12T00:00:00+00:00 [running]> on host 72ec96fe1e37
[2025-08-12T12:38:05.139+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='solar_flares_train_12h' AIRFLOW_CTX_TASK_ID='mlflow_ping' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-12T00:00:00+00:00'
[2025-08-12T12:38:05.140+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T12:38:05.152+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T12:38:05.154+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "\npython - <<'PY'\nimport os, mlflow, time\nprint('URI:', os.getenv('MLFLOW_TRACKING_URI'))\nmlflow.set_tracking_uri(os.getenv('MLFLOW_TRACKING_URI'))\nwith mlflow.start_run(run_name='***-ping-' + time.strftime('%Y%m%d-%H%M%S')):\n    mlflow.log_param('ping','ok')\nprint('OK')\nPY"]
[2025-08-12T12:38:05.166+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T12:38:06.876+0000] {subprocess.py:93} INFO - 2025/08/12 12:38:06 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2025-08-12T12:38:06.877+0000] {subprocess.py:93} INFO - The git executable must be specified in one of the following ways:
[2025-08-12T12:38:06.877+0000] {subprocess.py:93} INFO -     - be included in your $PATH
[2025-08-12T12:38:06.878+0000] {subprocess.py:93} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2025-08-12T12:38:06.878+0000] {subprocess.py:93} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2025-08-12T12:38:06.878+0000] {subprocess.py:93} INFO - 
[2025-08-12T12:38:06.879+0000] {subprocess.py:93} INFO - All git commands will error until this is rectified.
[2025-08-12T12:38:06.879+0000] {subprocess.py:93} INFO - 
[2025-08-12T12:38:06.879+0000] {subprocess.py:93} INFO - This initial message can be silenced or aggravated in the future by setting the
[2025-08-12T12:38:06.879+0000] {subprocess.py:93} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2025-08-12T12:38:06.880+0000] {subprocess.py:93} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2025-08-12T12:38:06.880+0000] {subprocess.py:93} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2025-08-12T12:38:06.880+0000] {subprocess.py:93} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2025-08-12T12:38:06.881+0000] {subprocess.py:93} INFO - 
[2025-08-12T12:38:06.881+0000] {subprocess.py:93} INFO - Example:
[2025-08-12T12:38:06.881+0000] {subprocess.py:93} INFO -     export GIT_PYTHON_REFRESH=quiet
[2025-08-12T12:38:06.882+0000] {subprocess.py:93} INFO - 
[2025-08-12T12:38:07.128+0000] {subprocess.py:93} INFO - URI: http://mlflow:5000
[2025-08-12T12:38:07.129+0000] {subprocess.py:93} INFO - OK
[2025-08-12T12:38:07.348+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-12T12:38:07.349+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T12:38:07.376+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=solar_flares_train_12h, task_id=mlflow_ping, run_id=scheduled__2025-08-12T00:00:00+00:00, execution_date=20250812T000000, start_date=20250812T123804, end_date=20250812T123807
[2025-08-12T12:38:07.396+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-12T12:38:07.419+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-12T12:38:07.422+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
