[2025-08-09T19:56:49.250+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-09T19:56:49.294+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xrs_update_12h.dq_quick manual__2025-08-09T19:53:05+00:00 [queued]>
[2025-08-09T19:56:49.303+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xrs_update_12h.dq_quick manual__2025-08-09T19:53:05+00:00 [queued]>
[2025-08-09T19:56:49.311+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-08-09T19:56:49.326+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dq_quick> on 2025-08-09 19:53:05+00:00
[2025-08-09T19:56:49.338+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xrs_update_12h', 'dq_quick', 'manual__2025-08-09T19:53:05+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/xrs_update_daily.py', '--cfg-path', '/tmp/tmpm4sw1qrv']
[2025-08-09T19:56:49.342+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask dq_quick
[2025-08-09T19:56:49.342+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=259) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-09T19:56:49.344+0000] {standard_task_runner.py:63} INFO - Started process 260 to run task
[2025-08-09T19:56:49.417+0000] {task_command.py:426} INFO - Running <TaskInstance: xrs_update_12h.dq_quick manual__2025-08-09T19:53:05+00:00 [running]> on host 9d4e07229e62
[2025-08-09T19:56:49.555+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='xrs_update_12h' AIRFLOW_CTX_TASK_ID='dq_quick' AIRFLOW_CTX_EXECUTION_DATE='2025-08-09T19:53:05+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-09T19:53:05+00:00'
[2025-08-09T19:56:49.556+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-09T19:56:49.572+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-09T19:56:49.577+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "python - <<'PY'\nimport os, pandas as pd\nroot = os.environ.get('PROJECT_ROOT', '/opt/project')\npath = os.path.join(root, 'data', 'xrs_clean.parquet')\nprint('reading:', path)\ndf = pd.read_parquet(path)\nprint('shape:', df.shape)\nprint('nulls:\\n', df.isna().sum().sort_values(ascending=False).to_string())\nprint('by satellite:\\n', df.groupby('satellite')['time'].agg(['min','max','count']))\nPY"]
[2025-08-09T19:56:49.596+0000] {subprocess.py:86} INFO - Output:
[2025-08-09T19:56:50.425+0000] {subprocess.py:93} INFO - reading: /opt/project/data/xrs_clean.parquet
[2025-08-09T19:56:50.426+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-09T19:56:50.426+0000] {subprocess.py:93} INFO -   File "<stdin>", line 5, in <module>
[2025-08-09T19:56:50.427+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
[2025-08-09T19:56:50.427+0000] {subprocess.py:93} INFO -     return impl.read(
[2025-08-09T19:56:50.427+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^
[2025-08-09T19:56:50.428+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 265, in read
[2025-08-09T19:56:50.428+0000] {subprocess.py:93} INFO -     path_or_handle, handles, filesystem = _get_path_or_handle(
[2025-08-09T19:56:50.429+0000] {subprocess.py:93} INFO -                                           ^^^^^^^^^^^^^^^^^^^^
[2025-08-09T19:56:50.429+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
[2025-08-09T19:56:50.430+0000] {subprocess.py:93} INFO -     handles = get_handle(
[2025-08-09T19:56:50.430+0000] {subprocess.py:93} INFO -               ^^^^^^^^^^^
[2025-08-09T19:56:50.431+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/common.py", line 872, in get_handle
[2025-08-09T19:56:50.431+0000] {subprocess.py:93} INFO -     handle = open(handle, ioargs.mode)
[2025-08-09T19:56:50.432+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-09T19:56:50.432+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/opt/project/data/xrs_clean.parquet'
[2025-08-09T19:56:50.530+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-09T19:56:50.532+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-09T19:56:50.549+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-09T19:56:50.555+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=xrs_update_12h, task_id=dq_quick, run_id=manual__2025-08-09T19:53:05+00:00, execution_date=20250809T195305, start_date=20250809T195649, end_date=20250809T195650
[2025-08-09T19:56:50.580+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task dq_quick (Bash command failed. The command returned a non-zero exit code 1.; 260)
[2025-08-09T19:56:50.605+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-09T19:56:50.629+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-09T19:56:50.640+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
